version: '3.8'
services:
  db:
    container_name: nextjs-nodejs-db
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data   # Persistent database storage
    ports:
      - "5433:5432"

  backend:
    build: ./back-end
    env_file: .env
    volumes:
      - ./back-end:/app
      - /app/node_modules
    ports:
      - "13000:3000"
    depends_on:
      - db
